export interface Destination {
  id: string;
  name: string;
  slug: string;
  flag: string;
  image: string;
  tagline: string;
  highlights: string[];
  tuitionRange: string;
  visaSuccessRate: string;
  workRights: string;
  popularCourses: string[];
  tags: string[];
}

export const DESTINATIONS: Destination[] = [
  {
    id: "uk",
    name: "United Kingdom",
    slug: "uk",
    flag: "🇬🇧",
    image: "/images/destinations/uk.png",
    tagline: "World-class universities and a global career launchpad.",
    highlights: ["Post-study work visa (2 yrs)", "Russell Group universities", "Rich cultural heritage"],
    tuitionRange: "£12,000 – £38,000/yr",
    visaSuccessRate: "94%",
    workRights: "20 hrs/week during term",
    popularCourses: ["Business", "Engineering", "Law", "Medicine"],
    tags: ["Popular", "Work Opportunities", "Scholarships"],
  },
  {
    id: "usa",
    name: "United States",
    slug: "usa",
    flag: "🇺🇸",
    image: "/images/destinations/usa.png",
    tagline: "Premier research institutions and unmatched diversity.",
    highlights: ["OPT work authorization", "Ivy League access", "Flexible curriculum"],
    tuitionRange: "$20,000 – $55,000/yr",
    visaSuccessRate: "89%",
    workRights: "20 hrs/week on campus",
    popularCourses: ["Computer Science", "Business", "Engineering", "Arts"],
    tags: ["Popular", "Scholarships"],
  },
  {
    id: "ca",
    name: "Canada",
    slug: "canada",
    flag: "🇨🇦",
    image: "/images/destinations/canada.png",
    tagline: "Affordable education with a clear path to residency.",
    highlights: ["3-yr post-study work permit", "PR pathway", "Affordable tuition"],
    tuitionRange: "CAD 15,000 – 35,000/yr",
    visaSuccessRate: "92%",
    workRights: "20 hrs/week during term",
    popularCourses: ["IT", "Healthcare", "Business", "Engineering"],
    tags: ["Popular", "Affordable", "Work Opportunities", "High Visa Success"],
  },
  {
    id: "au",
    name: "Australia",
    slug: "australia",
    flag: "🇦🇺",
    image: "/images/destinations/australia.png",
    tagline: "Innovative universities and a welcoming lifestyle.",
    highlights: ["Post-study work visa (2–4 yrs)", "High quality of life", "Strong job market"],
    tuitionRange: "AUD 20,000 – 45,000/yr",
    visaSuccessRate: "91%",
    workRights: "48 hrs/fortnight",
    popularCourses: ["Nursing", "IT", "Engineering", "Business"],
    tags: ["Popular", "Work Opportunities"],
  },
  {
    id: "de",
    name: "Germany",
    slug: "germany",
    flag: "🇩🇪",
    image: "/images/destinations/germany.png",
    tagline: "Tuition-free education and engineering excellence.",
    highlights: ["Free/low tuition at public unis", "18-month job seeker visa", "Engineering hub"],
    tuitionRange: "€0 – €1,500/semester",
    visaSuccessRate: "90%",
    workRights: "120 full days/year",
    popularCourses: ["Engineering", "Computer Science", "Automotive", "Physics"],
    tags: ["Affordable", "Work Opportunities", "Scholarships"],
  },
  {
    id: "ie",
    name: "Ireland",
    slug: "ireland",
    flag: "🇮🇪",
    image: "/images/destinations/ireland.png",
    tagline: "English-speaking EU hub with thriving tech companies.",
    highlights: ["Stay-back visa (1–2 yrs)", "Tech & pharma hub", "English-speaking"],
    tuitionRange: "€10,000 – €25,000/yr",
    visaSuccessRate: "93%",
    workRights: "20 hrs/week during term",
    popularCourses: ["IT", "Pharma", "Business", "Data Science"],
    tags: ["Work Opportunities", "High Visa Success"],
  },
  {
    id: "nl",
    name: "Netherlands",
    slug: "netherlands",
    flag: "🇳🇱",
    image: "/images/destinations/netherlands.png",
    tagline: "Progressive education in the heart of Europe.",
    highlights: ["Orientation year visa", "English-taught programs", "Compact & connected"],
    tuitionRange: "€8,000 – €20,000/yr",
    visaSuccessRate: "92%",
    workRights: "16 hrs/week",
    popularCourses: ["Business", "Engineering", "Social Sciences", "Design"],
    tags: ["Affordable", "Scholarships"],
  },
  {
    id: "pl",
    name: "Poland",
    slug: "poland",
    flag: "🇵🇱",
    image: "/images/destinations/poland.png",
    tagline: "Affordable medical and technical studies in the EU.",
    highlights: ["Low tuition fees", "Rich academic history", "Gateway to EU"],
    tuitionRange: "€2,000 – €5,000/yr",
    visaSuccessRate: "90%",
    workRights: "20 hrs/week",
    popularCourses: ["Medicine", "Engineering", "IT", "Business"],
    tags: ["Affordable", "Work Opportunities"],
  },
  {
    id: "dubai",
    name: "Dubai (UAE)",
    slug: "dubai",
    flag: "🇦🇪",
    image: "/images/destinations/dubai.png",
    tagline: "A global commercial hub with top branch universities.",
    highlights: ["Tax-free environment", "Modern lifestyle", "Global networking"],
    tuitionRange: "$15,000 – $30,000/yr",
    visaSuccessRate: "95%",
    workRights: "Visit with student permit",
    popularCourses: ["Business", "Hospitality", "Logistics"],
    tags: ["Popular", "Work Opportunities"],
  },
  {
    id: "sk",
    name: "South Korea",
    slug: "south-korea",
    flag: "🇰🇷",
    image: "/images/destinations/korea.png",
    tagline: "High-tech innovation meets vibrant traditional culture.",
    highlights: ["Top-tier research", "Safe environment", "K-Culture hub"],
    tuitionRange: "$4,000 – $10,000/yr",
    visaSuccessRate: "91%",
    workRights: "20 hrs/week",
    popularCourses: ["Engineering", "Media", "Arts"],
    tags: ["Scholarships", "Popular"],
  },
  {
    id: "mt",
    name: "Malta",
    slug: "malta",
    flag: "🇲🇹",
    image: "/images/destinations/malta.png",
    tagline: "English-speaking Mediterranean destination in the EU.",
    highlights: ["English-taught courses", "Sunny climate", "Affordable living"],
    tuitionRange: "€6,000 – €12,000/yr",
    visaSuccessRate: "92%",
    workRights: "15 hrs/week after 90 days",
    popularCourses: ["Tourism", "Business", "IT"],
    tags: ["Affordable", "High Visa Success"],
  },
  {
    id: "tr",
    name: "Turkey",
    slug: "turkey",
    flag: "🇹🇷",
    image: "/images/destinations/turkey.png",
    tagline: "Bridge between East and West with modern campuses.",
    highlights: ["Cultural diversity", "Modern universities", "Affordable costs"],
    tuitionRange: "$1,000 – $8,000/yr",
    visaSuccessRate: "89%",
    workRights: "Restricted part-time",
    popularCourses: ["Architecture", "Engineering", "Medicine"],
    tags: ["Affordable", "Popular"],
  },
  {
    id: "fr",
    name: "France",
    slug: "france",
    flag: "🇫🇷",
    image: "/images/destinations/france.png",
    tagline: "Prestigious grandes écoles and affordable living.",
    highlights: ["Low tuition at public unis", "2-yr post-study visa", "Rich culture"],
    tuitionRange: "€3,000 – €20,000/yr",
    visaSuccessRate: "88%",
    workRights: "964 hrs/year",
    popularCourses: ["Business", "Fashion", "Engineering", "Hospitality"],
    tags: ["Affordable", "Scholarships"],
  },
];

export const FILTER_TAGS = ["Popular", "Affordable", "High Visa Success", "Work Opportunities", "Scholarships"];
